In [59]:
import pandas as pd

In [60]:

import matplotlib.pyplot as plt
import numpy as np

In [61]:
datas=pd.read_csv(r"C:\Users\ssuba\OneDrive\Desktop\TECH PANDAS\MACHINE LEARNING\17_OCT_2026_DECESION_TREE\50_Startups_dataset.csv")

In [62]:
datas

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,State,Profit
0,0,165349.30,136897.90,471784.20,New York,192261.93
1,1,162597.80,151377.69,443898.63,California,191792.16
2,2,153441.61,101145.65,407934.64,Florida,191050.49
3,3,144372.51,118671.95,383199.72,New York,182902.09
4,4,142107.44,91391.87,366168.52,Florida,166188.04
5,5,131877.00,99814.81,362861.46,New York,156991.22
6,6,134615.56,147198.97,127716.92,California,156122.61
7,7,130298.23,145530.16,323876.78,Florida,155752.70
8,8,120542.62,148719.05,311613.39,New York,152211.87
9,9,123334.98,108679.27,304981.72,California,149760.06
10,10,101913.18,110594.21,229161.05,Florida,146122.05
11,11,100672.06,91790.71,249744.65,California,144259.50
12,12,93863.85,127320.48,249839.54,Florida,141585.62
13,13,91992.49,135495.17,252665.03,California,134307.45
14,14,119943.34,156547.52,256513.02,Florida,132602.75
15,15,114523.71,122616.94,261776.33,New York,129917.14
16,16,78013.21,121597.65,264346.16,California,126993.03
17,17,94657.26,145077.68,282574.41,New York,125370.47
18,18,91749.26,114175.89,294919.67,Florida,124267.00
19,19,86419.80,153514.21,0.10,New York,122776.96
20,20,76253.96,113867.40,298664.57,California,118474.13
21,21,78389.57,153773.53,299737.39,New York,111313.12
22,22,73994.66,122782.85,303319.36,Florida,110352.35
23,23,67532.63,105751.13,304768.83,Florida,108734.09
24,24,77044.11,99281.44,140574.91,New York,108552.14
25,25,64664.81,139553.26,137962.72,California,107404.44
26,26,75328.97,144136.08,134050.17,Florida,105733.64
27,27,72107.70,127864.65,353183.91,New York,105008.41
28,28,66051.62,182645.66,118148.30,Florida,103282.48
29,29,65605.58,153032.16,107138.48,New York,101004.74
30,30,61994.58,115641.38,91131.34,Florida,99937.69
31,31,61136.48,152702.02,88218.33,New York,97483.66
32,32,63408.96,129219.71,46085.35,California,97427.94
33,33,55494.05,103057.59,214634.91,Florida,96779.02
34,34,46426.17,157694.02,210797.77,California,96712.90
35,35,46014.12,85047.54,205517.74,New York,96479.61
36,36,28663.86,127056.31,201126.92,Florida,90708.29
37,37,44070.05,51283.24,197029.52,California,89949.24
38,38,20229.69,65948.03,185265.20,New York,81229.16
39,39,38558.61,82982.19,174999.40,California,81005.86
40,40,28754.43,118546.15,172795.77,California,78240.01
41,41,27893.02,84710.87,164470.81,Florida,77798.93
42,42,23641.03,96189.73,148001.21,California,71498.59
43,43,15505.83,127382.40,35534.27,New York,69759.08
44,44,22177.84,154806.24,28334.82,California,65200.43
45,45,1000.33,124153.14,1904.03,New York,64926.18
46,46,1315.56,115816.31,297114.56,Florida,49490.85
47,47,0.10,135427.02,0.10,California,42559.83
48,48,542.15,51743.25,0.10,New York,35673.51
49,49,0.10,116983.90,45173.16,California,14681.50

In [63]:
datas=pd.get_dummies( datas,drop_first=True)

In [64]:
datas

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,0,165349.30,136897.90,471784.20,192261.93,False,True
1,1,162597.80,151377.69,443898.63,191792.16,False,False
2,2,153441.61,101145.65,407934.64,191050.49,True,False
3,3,144372.51,118671.95,383199.72,182902.09,False,True
4,4,142107.44,91391.87,366168.52,166188.04,True,False
5,5,131877.00,99814.81,362861.46,156991.22,False,True
6,6,134615.56,147198.97,127716.92,156122.61,False,False
7,7,130298.23,145530.16,323876.78,155752.70,True,False
8,8,120542.62,148719.05,311613.39,152211.87,False,True
9,9,123334.98,108679.27,304981.72,149760.06,False,False
10,10,101913.18,110594.21,229161.05,146122.05,True,False
11,11,100672.06,91790.71,249744.65,144259.50,False,False
12,12,93863.85,127320.48,249839.54,141585.62,True,False
13,13,91992.49,135495.17,252665.03,134307.45,False,False
14,14,119943.34,156547.52,256513.02,132602.75,True,False
15,15,114523.71,122616.94,261776.33,129917.14,False,True
16,16,78013.21,121597.65,264346.16,126993.03,False,False
17,17,94657.26,145077.68,282574.41,125370.47,False,True
18,18,91749.26,114175.89,294919.67,124267.00,True,False
19,19,86419.80,153514.21,0.10,122776.96,False,True
20,20,76253.96,113867.40,298664.57,118474.13,False,False
21,21,78389.57,153773.53,299737.39,111313.12,False,True
22,22,73994.66,122782.85,303319.36,110352.35,True,False
23,23,67532.63,105751.13,304768.83,108734.09,True,False
24,24,77044.11,99281.44,140574.91,108552.14,False,True
25,25,64664.81,139553.26,137962.72,107404.44,False,False
26,26,75328.97,144136.08,134050.17,105733.64,True,False
27,27,72107.70,127864.65,353183.91,105008.41,False,True
28,28,66051.62,182645.66,118148.30,103282.48,True,False
29,29,65605.58,153032.16,107138.48,101004.74,False,True
30,30,61994.58,115641.38,91131.34,99937.69,True,False
31,31,61136.48,152702.02,88218.33,97483.66,False,True
32,32,63408.96,129219.71,46085.35,97427.94,False,False
33,33,55494.05,103057.59,214634.91,96779.02,True,False
34,34,46426.17,157694.02,210797.77,96712.90,False,False
35,35,46014.12,85047.54,205517.74,96479.61,False,True
36,36,28663.86,127056.31,201126.92,90708.29,True,False
37,37,44070.05,51283.24,197029.52,89949.24,False,False
38,38,20229.69,65948.03,185265.20,81229.16,False,True
39,39,38558.61,82982.19,174999.40,81005.86,False,False
40,40,28754.43,118546.15,172795.77,78240.01,False,False
41,41,27893.02,84710.87,164470.81,77798.93,True,False
42,42,23641.03,96189.73,148001.21,71498.59,False,False
43,43,15505.83,127382.40,35534.27,69759.08,False,True
44,44,22177.84,154806.24,28334.82,65200.43,False,False
45,45,1000.33,124153.14,1904.03,64926.18,False,True
46,46,1315.56,115816.31,297114.56,49490.85,True,False
47,47,0.10,135427.02,0.10,42559.83,False,False
48,48,542.15,51743.25,0.10,35673.51,False,True
49,49,0.10,116983.90,45173.16,14681.50,False,False

In [ ]:
datas = pd.get_dummies (datas,drop_first = True)

In [ ]:
datas

,Unnamed: 0,R&D Spend,Administration,Marketing Spend,Profit,State_Florida,State_New York
0,0,165349.30,136897.90,471784.20,192261.93,False,True
1,1,162597.80,151377.69,443898.63,191792.16,False,False
2,2,153441.61,101145.65,407934.64,191050.49,True,False
3,3,144372.51,118671.95,383199.72,182902.09,False,True
4,4,142107.44,91391.87,366168.52,166188.04,True,False
5,5,131877.00,99814.81,362861.46,156991.22,False,True
6,6,134615.56,147198.97,127716.92,156122.61,False,False
7,7,130298.23,145530.16,323876.78,155752.70,True,False
8,8,120542.62,148719.05,311613.39,152211.87,False,True
9,9,123334.98,108679.27,304981.72,149760.06,False,False
10,10,101913.18,110594.21,229161.05,146122.05,True,False
11,11,100672.06,91790.71,249744.65,144259.50,False,False
12,12,93863.85,127320.48,249839.54,141585.62,True,False
13,13,91992.49,135495.17,252665.03,134307.45,False,False
14,14,119943.34,156547.52,256513.02,132602.75,True,False
15,15,114523.71,122616.94,261776.33,129917.14,False,True
16,16,78013.21,121597.65,264346.16,126993.03,False,False
17,17,94657.26,145077.68,282574.41,125370.47,False,True
18,18,91749.26,114175.89,294919.67,124267.00,True,False
19,19,86419.80,153514.21,0.10,122776.96,False,True
20,20,76253.96,113867.40,298664.57,118474.13,False,False
21,21,78389.57,153773.53,299737.39,111313.12,False,True
22,22,73994.66,122782.85,303319.36,110352.35,True,False
23,23,67532.63,105751.13,304768.83,108734.09,True,False
24,24,77044.11,99281.44,140574.91,108552.14,False,True
25,25,64664.81,139553.26,137962.72,107404.44,False,False
26,26,75328.97,144136.08,134050.17,105733.64,True,False
27,27,72107.70,127864.65,353183.91,105008.41,False,True
28,28,66051.62,182645.66,118148.30,103282.48,True,False
29,29,65605.58,153032.16,107138.48,101004.74,False,True
30,30,61994.58,115641.38,91131.34,99937.69,True,False
31,31,61136.48,152702.02,88218.33,97483.66,False,True
32,32,63408.96,129219.71,46085.35,97427.94,False,False
33,33,55494.05,103057.59,214634.91,96779.02,True,False
34,34,46426.17,157694.02,210797.77,96712.90,False,False
35,35,46014.12,85047.54,205517.74,96479.61,False,True
36,36,28663.86,127056.31,201126.92,90708.29,True,False
37,37,44070.05,51283.24,197029.52,89949.24,False,False
38,38,20229.69,65948.03,185265.20,81229.16,False,True
39,39,38558.61,82982.19,174999.40,81005.86,False,False
40,40,28754.43,118546.15,172795.77,78240.01,False,False
41,41,27893.02,84710.87,164470.81,77798.93,True,False
42,42,23641.03,96189.73,148001.21,71498.59,False,False
43,43,15505.83,127382.40,35534.27,69759.08,False,True
44,44,22177.84,154806.24,28334.82,65200.43,False,False
45,45,1000.33,124153.14,1904.03,64926.18,False,True
46,46,1315.56,115816.31,297114.56,49490.85,True,False
47,47,0.10,135427.02,0.10,42559.83,False,False
48,48,542.15,51743.25,0.10,35673.51,False,True
49,49,0.10,116983.90,45173.16,14681.50,False,False

In [ ]:
datas.columns

Index(['Unnamed: 0', 'R&D Spend', 'Administration', 'Marketing Spend',
       'Profit', 'State_Florida', 'State_New York'],
      dtype='object')

In [ ]:
independent = datas [['R&D Spend', 'Administration', 'Marketing Spend','State_Florida', 'State_New York']]
dependent = datas [['Profit']]

In [ ]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in c:\users\ssuba\appdata\local\programs\python\python310\lib\site-packages (1.7.2)
Requirement already satisfied: threadpoolctl>=3.1.0 in c:\users\ssuba\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: numpy>=1.22.0 in c:\users\ssuba\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (2.2.6)
Requirement already satisfied: joblib>=1.2.0 in c:\users\ssuba\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: scipy>=1.8.0 in c:\users\ssuba\appdata\local\programs\python\python310\lib\site-packages (from scikit-learn) (1.15.3)
Requirement already satisfied: cloudpickle>=3.0 in c:\users\ssuba\appdata\local\programs\python\python310\lib\site-packages (from joblib>=1.2.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 23.0.1 -> 26.2.2
[notice] To update, run: python.exe -m pip install --upgrade pip

In [ ]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(independent, dependent, test_size= 1/3, random_state=0)

In [ ]:
x_train

    R&D Spend  Administration  Marketing Spend  State_Florida  State_New York
45    1000.33       124153.14          1904.03          False            True
48     542.15        51743.25             0.10          False            True
29   65605.58       153032.16        107138.48          False            True
15  114523.71       122616.94        261776.33          False            True
30   61994.58       115641.38         91131.34           True           False
32   63408.96       129219.71         46085.35          False           False
16   78013.21       121597.65        264346.16          False           False
42   23641.03        96189.73        148001.21          False           False
20   76253.96       113867.40        298664.57          False           False
43   15505.83       127382.40         35534.27          False            True
8   120542.62       148719.05        311613.39          False            True
13   91992.49       135495.17        252665.03          False           False
25   64664.81       139553.26        137962.72          False           False
5   131877.00        99814.81        362861.46          False            True
17   94657.26       145077.68        282574.41          False            True
40   28754.43       118546.15        172795.77          False           False
49       0.10       116983.90         45173.16          False           False
1   162597.80       151377.69        443898.63          False           False
12   93863.85       127320.48        249839.54           True           False
37   44070.05        51283.24        197029.52          False           False
24   77044.11        99281.44        140574.91          False            True
6   134615.56       147198.97        127716.92          False           False
23   67532.63       105751.13        304768.83           True           False
36   28663.86       127056.31        201126.92           True           False
21   78389.57       153773.53        299737.39          False            True
19   86419.80       153514.21             0.10          False            True
9   123334.98       108679.27        304981.72          False           False
39   38558.61        82982.19        174999.40          False           False
46    1315.56       115816.31        297114.56           True           False
3   144372.51       118671.95        383199.72          False            True
0   165349.30       136897.90        471784.20          False            True
47       0.10       135427.02             0.10          False           False
44   22177.84       154806.24         28334.82          False           False

In [ ]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train = sc.fit_transform( x_train )
x_test = sc.transform(x_test)

In [ ]:
x_train

array([[-1.41859108,  0.08007161, -1.46280061, -0.42257713,  1.24034735],
       [-1.42804718, -2.75105709, -1.4772005 , -0.42257713,  1.24034735],
       [-0.08524282,  1.20920221, -0.66688679, -0.42257713,  1.24034735],
       [ 0.92434855,  0.02000827,  0.50267699, -0.42257713,  1.24034735],
       [-0.15976805, -0.25272669, -0.7879527 ,  2.36643191, -0.80622577],
       [-0.13057752,  0.27816764, -1.12864651, -0.42257713, -0.80622577],
       [ 0.17083067, -0.01984459,  0.52211324, -0.42257713, -0.80622577],
       [-0.95132351, -1.01325988, -0.357832  , -0.42257713, -0.80622577],
       [ 0.13452258, -0.3220869 ,  0.78167175, -0.42257713, -0.80622577],
       [-1.11922093,  0.20633131, -1.2084469 , -0.42257713,  1.24034735],
       [ 1.04856916,  1.04056545,  0.87960683, -0.42257713,  1.24034735],
       [ 0.45934048,  0.52352964,  0.433766  , -0.42257713, -0.80622577],
       [-0.1046588 ,  0.68219546, -0.43375555, -0.42257713, -0.80622577],
       [ 1.2824925 , -0.87152415,  1.26720849, -0.42257713,  1.24034735],
       [ 0.51433704,  0.89819281,  0.65997794, -0.42257713,  1.24034735],
       [-0.84579118, -0.13915411, -0.17030469, -0.42257713, -0.80622577],
       [-1.43923421, -0.20023597, -1.13554563, -0.42257713, -0.80622577],
       [ 1.9165203 ,  1.14451467,  1.88011237, -0.42257713, -0.80622577],
       [ 0.49796233,  0.20391032,  0.41239613,  2.36643191, -0.80622577],
       [-0.52970146, -2.76904286,  0.01298107, -0.42257713, -0.80622577],
       [ 0.15083   , -0.8923782 , -0.41399892, -0.42257713,  1.24034735],
       [ 1.33901196,  0.98113238, -0.51124703, -0.42257713, -0.80622577],
       [-0.04547162, -0.63942208,  0.82783976,  2.36643191, -0.80622577],
       [-0.8476604 ,  0.19358163,  0.04397071,  2.36643191, -0.80622577],
       [ 0.17859813,  1.23818877,  0.78978575, -0.42257713,  1.24034735],
       [ 0.34432914,  1.22804971, -1.4772005 , -0.42257713,  1.24034735],
       [ 1.10619897, -0.52493576,  0.82944989, -0.42257713, -0.80622577],
       [-0.6434487 , -1.52965682, -0.1536381 , -0.42257713, -0.80622577],
       [-1.41208524, -0.24588716,  0.76994864,  2.36643191, -0.80622577],
       [ 1.54037969, -0.1342355 ,  1.42103171, -0.42257713,  1.24034735],
       [ 1.97330683,  0.57837448,  2.09101774, -0.42257713,  1.24034735],
       [-1.43923421,  0.52086506, -1.4772005 , -0.42257713, -0.80622577],
       [-0.9815214 ,  1.27856634, -1.2628981 , -0.42257713, -0.80622577]])

In [90]:
from sklearn.svm import SVR
regressor=SVR(kernel='linear' , gamma= 'scale' , C= 100000 )
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000, kernel='linear')

In [91]:
y_pred= regressor.predict(x_test)
y_pred

array([107510.35960602, 133181.98210526, 136172.42428029,  75880.15032355,
       182829.14552265, 115793.82960477,  65868.57343981,  96748.02774677,
       118949.2030055 , 171877.30430037,  99961.84028969,  87261.62894024,
       113374.88575743,  93532.04434769, 131607.70376248, 163668.80787573,
       153321.93357301])

In [92]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [94]:
r_score

0.9082817413813681

In [112]:
from sklearn.svm import SVR
regressor=SVR(kernel='linear' , gamma= 'auto' , C=100000)
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000, gamma='auto', kernel='linear')

In [113]:
y_pred= regressor.predict(x_test)
y_pred

array([107510.35960602, 133181.98210526, 136172.42428029,  75880.15032355,
       182829.14552265, 115793.82960477,  65868.57343981,  96748.02774677,
       118949.2030055 , 171877.30430037,  99961.84028969,  87261.62894024,
       113374.88575743,  93532.04434769, 131607.70376248, 163668.80787573,
       153321.93357301])

In [114]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [115]:
r_score

0.9082817413813681

In [155]:
from sklearn.svm import SVR
regressor=SVR(kernel='poly' , gamma= 'scale' , C= 100000)
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000, kernel='poly')

In [156]:
y_pred= regressor.predict(x_test)
y_pred

array([ 88146.24302627, 134605.2092532 , 137555.59167094,  43337.3120096 ,
       272339.61869544, 112802.73706216,  60117.68038048,  96497.4396745 ,
       128338.35632263, 232870.75141057,  92031.96228264,  96902.87623598,
       116862.11471894, 104922.67684145, 138725.35641968, 216557.64814762,
       193468.91328491])

In [157]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [158]:
r_score

-0.32015487237052764

In [ ]:
from sklearn.svm import SVR
regressor=SVR(kernel='poly' , gamma= 'scale' , C= 100000)
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000, gamma='auto', kernel='poly')

In [178]:
y_pred= regressor.predict(x_test)
y_pred

array([ 88146.24302627, 134605.2092532 , 137555.59167094,  43337.3120096 ,
       272339.61869544, 112802.73706216,  60117.68038048,  96497.4396745 ,
       128338.35632263, 232870.75141057,  92031.96228264,  96902.87623598,
       116862.11471894, 104922.67684145, 138725.35641968, 216557.64814762,
       193468.91328491])

In [179]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [ ]:
r_score

-0.32015487237054163

In [205]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf' , gamma= 'scale' , C= 100000)
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000)

In [206]:
y_pred= regressor.predict(x_test)
y_pred

array([120052.81624826, 122316.26577497, 133242.46704116,  73437.26848039,
       137001.08257499, 114519.7252237 ,  70186.12191767,  99276.33839689,
       125877.67455363, 131861.09439055,  95561.40413404,  90502.04186227,
       127940.03823876,  98151.41608047, 132778.78132265, 155607.39281301,
       150719.47803635])

In [207]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [208]:
r_score

0.600915828447055

In [228]:
from sklearn.svm import SVR
regressor=SVR(kernel='rbf' , gamma= 'auto' , C= 100000)
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000, gamma='auto')

In [229]:
y_pred= regressor.predict(x_test)
y_pred

array([120052.81624826, 122316.26577497, 133242.46704116,  73437.26848039,
       137001.08257499, 114519.7252237 ,  70186.12191767,  99276.33839689,
       125877.67455363, 131861.09439055,  95561.40413404,  90502.04186227,
       127940.03823876,  98151.41608047, 132778.78132265, 155607.39281301,
       150719.47803635])

In [230]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [231]:
r_score

0.6009158284470548

In [248]:
from sklearn.svm import SVR
regressor=SVR(kernel='sigmoid' , gamma= 'scale' , C= 100000)
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000, kernel='sigmoid')

In [249]:
y_pred= regressor.predict(x_test)
y_pred

array([105036.43565136, 137855.33156006, 148872.07206371, 125121.78642845,
       240829.87902284, 144114.03440648,  42115.77345728, 118788.44290973,
       142814.05275093, 243791.00684021, 124543.42573854, 117627.68908522,
        84224.00095144,  76614.86408527, 161098.24337285, 189158.85017587,
       181273.58560666])

In [250]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [251]:
r_score

-0.3815624781680982

In [270]:
from sklearn.svm import SVR
regressor=SVR(kernel='sigmoid' , gamma= 'auto' , C=100000)
regressor.fit(x_train,y_train)

c:\Users\ssuba\AppData\Local\Programs\Python\Python310\lib\site-packages\sklearn\utils\validation.py:1406: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

SVR(C=100000, gamma='auto', kernel='sigmoid')

In [271]:
y_pred= regressor.predict(x_test)
y_pred

array([105036.43565136, 137855.33156006, 148872.07206371, 125121.78642845,
       240829.87902284, 144114.03440648,  42115.77345728, 118788.44290973,
       142814.05275093, 243791.00684021, 124543.42573854, 117627.68908522,
        84224.00095144,  76614.86408527, 161098.24337285, 189158.85017587,
       181273.58560666])

In [272]:
from sklearn.metrics import r2_score
r_score=r2_score(y_test,y_pred)

In [273]:
r_score

-0.3815624781681033